### ISSUE TITLE
We could not log you in - contact an admin.  [002] Failed to authenticate  Try Again →

### ISSUE THREAD

**Issue by MAS-CreativeLabs** [Mintplex-Labs/vector-admin#106]
Hello Everyone,

I hope this message finds you well.

I'm currently facing a challenge with an issue that was previously discussed  here.

I tried the solution previously listed

```
SYS_EMAIL="root@vectoradmin.com"
SYS_PASSWORD="password"
```
I also tried with hunter2

but it didn't work how did you guys get it to work?

I'm reaching out to inquire if anyone else has encountered a similar problem and, if so, how you managed to overcome it. Any insights or guidance would be greatly appreciated, as I'm keen on understanding the root cause and finding a viable solution.

Thank you for your time and assistance.

**Comment by timothycarambat** [comment]
- [ ] Ensure you have a database connected to the container via the `DATABASE_URL` environment variable and the connection string is correct
- [ ] On boot of the container the default credentials will be created which are `root@vectoradmin.com` and `password` unless otherwise defined on container start
https://github.com/Mintplex-Labs/vector-admin/blob/6cad8a30a1a89f645e02e0663ccf8832dfe87047/backend/utils/boot/index.js#L51-L52

**Comment by MAS-CreativeLabs** [comment]
Where do I set the `DATABASE_URL` environment variable? Should I add it to the `.env` file? 
What is the expected value for the variable?

**Comment by MAS-CreativeLabs** [comment]
Here's my docker-compose.yml: 

```
version: "3.9"
services:
  db:
    image: postgres
    container_name: vectoradmin-db
    hostname: vectoradmin-db
    mem_limit: 1g
    cpu_shares: 768
    ports:
      - 5433:5432
    networks:
      - vector-admin_default
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "vdbms", "-U", "vectoradminuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/projects/vectoradmin/db:/var/lib/postgresql/data:rw
    environment:
      TZ: America/Los_Angeles
      POSTGRES_DB: vdbms
      POSTGRES_USER: vectoradminuser
      POSTGRES_PASSWORD: vectoradminpass
    restart: on-failure:5

  vectoradmin:
    image: mintplexlabs/vectoradmin:master
    container_name: vector-admin
    hostname: vector-admin
    mem_limit: 2g
    cpu_shares: 768
    ports:
      - 4950:3001
    networks:
      - vector-admin_default
    extra_hosts:
      - host.docker.internal:host-gateway
    cap_add:
      - SYS_ADMIN
    volumes:
      - /volume1/docker/projects/vectoradmin:/app/backend/storage
      - /volume1/docker/projects/vectoradmin/.env:/app/backend/.env
    environment:
      SERVER_PORT: 3001
      DISABLE_TELEMETRY: true
      TZ: America/Los_Angeles
      JWT_SECRET: secret
      SYS_EMAIL: root@vectoradmin.com
      SYS_PASSWORD: password
      INNGEST_EVENT_KEY: background_workers
      INNGEST_SIGNING_KEY: secret
      INNGEST_LANDING_PAGE: true
      DATABASE_CONNECTION_STRING: postgresql://vectoradminuser:vectoradminpass@vectoradmin-db:5432/vdbms     
    depends_on:
      db:
        condition: service_healthy

networks:
  vector-admin_default:
    driver: bridge
    external: true

```


Here's my .env: 

```
SERVER_PORT="3001"
DISABLE_TELEMETRY="true"
TZ="America/Los_Angeles"
JWT_SECRET="secret"
SYS_EMAIL="root@vectoradmin.com"
SYS_PASSWORD="password"
INNGEST_EVENT_KEY="background_workers"
INNGEST_SIGNING_KEY="secret"
INNGEST_LANDING_PAGE="true"
DATABASE_CONNECTION_STRING="postgresql://vectoradminuser:vectoradminpass@vectoradmin-db:5432/vdbms"
```


Should I still add DATABASE_URL to the .env file? Wouldn't that be redundant with:

```DATABASE_CONNECTION_STRING="postgresql://vectoradminuser:vectoradminpass@vectoradmin-db:5432/vdbms"```
